<div id="view-disclaimer">      
    <h2 data-role="header" class="ui-header ui-bar-a ui-title" role="banner" role="heading" aria-level="1">Da Rulez</h2>
    <span class="closeBtn btn">X</span>
    <p>This website was built by order of the Artevelde University College Ghent.</p>
    <p>
        Nothing you find (either visual or technical) on this domain and/or website may be copied, used, 
        or tampered with without full consent and approval of its rightful authors.
    </p>
    <p>Website built with:
        <ul>
            <li>PHP [Zend Framework1] with MVC</li>
            <li>RESTful API on Slim framework</li>
            <li>MySQL</li>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>jQuery</li>
            <li>Canvas, Twitter Bootstrap, jQuery Mobile</li>
        </ul>
    </p>
    <p>
        Copyright by <a href="http://www.arteveldehogeschool.be" title="Artevelde University College" target="_blank">Artevelde University College Ghent</a>, 
        <br/>Stefaan Christiaens 2012-2013
    </p>
</div>