<?php 
    $this->inlineScript()
         ->appendFile($this->baseUrl('_scripts/js/answers.js')) 
         ->appendFile($this->baseUrl('_scripts/_libs/heatmaps/heatmap.js')) 
         ->appendFile($this->baseUrl('_scripts/_libs/heatmaps/heatmap-gmaps.js')) 
    ;
?>

<div class="span12 centered firstblock clearfix bottom-block" id='answers-title'>
    <div class="row">
        <div class="span12">
            <h1>Discover where to start</h1>
            <p class="lead lead-push">
                Answer all the questions to see where you'd fit best.<br/>
                <?php if($this->id == 0): ?>
                If you login first your result will be saved.
                <?php endif; ?>
            </p>
            <button class="btn btn-success btn-large" onclick='start();' title='Start answers'>START THE QUESTIONS</button>
        </div>
    </div>
</div>
<div class="span12 centered firstblock clearfix hide bottom-block" id='test'>
    <div class="row">
        <div class="span12 question" data-question='1'>
            <h1 class='text-center'>1. How old are you?</h1>
            <label class='radio' for='age1'><input type='radio' name='age' value='0' id='age1' />18 to 24 years old.</label> 
            <label class='radio' for='age2'><input type='radio' name='age' value='1' id='age2' />24 years old or older.</label> 
        </div>
        <div class="span12 question" data-question='2'>
            <h1 class='text-center'>2. Are you in need of a green environment?</h1>
            <label class='radio' for='park0'><input type='radio' name='park' value='0' id='park0'  />Yes, nature is my second name.</label> 
            <label class='radio' for='park1'><input type='radio' name='park' value='1' id='park1' />Yes, but I don't need it everyday.</label> 
            <label class='radio' for='park2'><input type='radio' name='park' value='2' id='park2' />No, not really.</label> 
        </div>
        <div class="span12 question" data-question='3'>
            <h1 class='text-center'>3. Do you have any kids?</h1>
            <label class='radio' for='child0'><input type='radio' name='child' value='0' id='child0'  />Yes, I have teenager kids.</label> 
            <label class='radio' for='child1'><input type='radio' name='child' value='1' id='child1' />Yes, I have little children.</label> 
            <label class='radio' for='child2'><input type='radio' name='child' value='2' id='child2' />Yes, but they already left the house.</label> 
            <label class='radio' for='child3'><input type='radio' name='child' value='3' id='child3' />Yes, they already left the house but I am planning to get a new baby.</label> 
            <label class='radio' for='child4'><input type='radio' name='child' value='4' id='child4' />No, but I am planning to get children soon.</label> 
            <label class='radio' for='child5'><input type='radio' name='child' value='5' id='child5' />No.</label> 
        </div>
        <div class="span12 question" data-question='4'>
            <h1 class='text-center'>4. Do you like to contribute to the neighborhood?</h1>
            <label class='radio' for='lux0'><input type='radio' name='lux' value='0' id='lux0'  />Yes, I want to participate weekly.</label> 
            <label class='radio' for='lux1'><input type='radio' name='lux' value='1' id='lux1' />Yes, but not to actively.</label> 
            <label class='radio' for='lux2'><input type='radio' name='lux' value='2' id='lux2' />No</label> 
        </div>
        <div class="span12 question" data-question='5'>
            <h1 class='text-center'>5. Do you take public transportation to work?</h1>
            <label class='radio' for='tran0'><input type='radio' name='tran' value='0' id='tran0'  />Yes</label> 
            <label class='radio' for='tran1'><input type='radio' name='tran' value='1' id='tran1' />No</label> 
        </div>
        <div class="span12 question" data-question='6'>
            <h1 class='text-center'>6. Do you like to read books?</h1>
            <label class='radio' for='bib0'><input type='radio' name='bib' value='0' id='bib0'  />Yes</label> 
            <label class='radio' for='bib1'><input type='radio' name='bib' value='1' id='bib1' />Yes, but I don't like to pay for them so I often go to the library.</label> 
            <label class='radio' for='bib2'><input type='radio' name='bib' value='2' id='bib2' />No</label> 
        </div>
        <div class="span12 question" data-question='7'>
            <h1 class='text-center'>7. Do you often work out?</h1>
            <label class='radio' for='sport0'><input type='radio' name='sport' value='0' id='sport0'  />Yes, I work out three times a week at least.</label> 
            <label class='radio' for='sport1'><input type='radio' name='sport' value='1' id='sport1' />Yes, every week.</label> 
            <label class='radio' for='sport2'><input type='radio' name='sport' value='2' id='sport2' />No, I am more the kind that works out for fun.</label> 
            <label class='radio' for='sport3'><input type='radio' name='sport' value='3' id='sport3' />No</label> 
        </div>
        <div class="span12 question" data-question='8'>
            <h1 class='text-center'>8. Do you drive a car?</h1>
            <label class='radio' for='car0'><input type='radio' name='car' value='0' id='car0'  />Yes, and I want a place with a garage.</label> 
            <label class='radio' for='car1'><input type='radio' name='car' value='1' id='car1' />Yes, but I always park my car in a public garage.</label> 
            <label class='radio' for='car2'><input type='radio' name='car' value='2' id='car2' />No.</label>
        </div>
        <div class="span12 question" data-question='9'>
            <h1 class='text-center'>9. Do you get support from the OCMW?</h1>
            <label class='radio' for='ocmw0'><input type='radio' name='ocmw' value='0' id='ocmw0'  />Yes</label> 
            <label class='radio' for='ocmw1'><input type='radio' name='ocmw' value='1' id='ocmw1' />No</label>
        </div>
        <div class="span12 question" data-question='10'>
            <h1 class='text-center'>10. Do you have pets?</h1>
            <label class='radio' for='dib0'><input type='radio' name='dib' value='0' id='dib0'  />Yes, a dog.</label> 
            <label class='radio' for='dib1'><input type='radio' name='dib' value='1' id='dib1' />Yes, but no dogs.</label>
            <label class='radio' for='dib2'><input type='radio' name='dib' value='2' id='dib2' />No.</label>
        </div>
        <div class="span12 question" data-question='11'>
            <h1 class='text-center'>11. Do you regularly go out to see a movie?</h1>
            <label class='radio' for='out1'><input type='radio' name='out' value='0' id='out1' />Yes, once every month.</label>
            <label class='radio' for='out2'><input type='radio' name='out' value='1' id='out2' />No</label>
        </div>
        <div class="span12">
            <ul class="pager">
                <li class="previous">
                    <a href="#" onclick='previous();'>&larr; Previous</a>
                </li>
                <li class="next">
                    <a href="#" onclick='next();'>Next &rarr;</a>
                </li>
            </ul>
        </div>
        
    </div>
</div>
<div class="span12 centered firstblock clearfix hide bottom-block" id='map_span'>
    <h1>These are the places we found suitable for you</h1>
    <div id="gmap"></div>
</div>
<script>
var _baseUrl = "<?php echo WEB_BASE_PATH; ?>";
<?php if($this->id != 0): ?>
var id = <?php echo $this->id; ?>;
var _loggedin = true;
<?php else: ?>
var _loggedin = false;   
<?php endif; ?>
</script>
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqsjbo0JTyqexEzIBOYcolZlo5SBUGrHc&sensor=false"></script>