<?php 
    $this->inlineScript()
         ->appendFile($this->baseUrl('_scripts/js/answers.js')); 
?>

<div class="span12 centered firstblock clearfix" id='answers-title'>
    <div class="row">
        <div class="span12">
            <h1>1. Discover where to start</h1>
            <p class="lead lead-push">
                Answer all the questions to see where you'd fit best.
            </p>
            <button class="btn btn-success btn-large" onclick='start();' title='Start answers'>START THE QUESTIONS</button>
        </div>
    </div>
</div>
<div class="span12 centered firstblock clearfix hide" id='test'>
    <div class="row">
        <div class="span12 question" data-question='1'>
            <h1 class='text-center'>1. How old are you?</h1>
            <label class='radio' for='age0'><input type='radio' name='age' value='0' id='age0' />&lt; 18 years old</label> 
            <label class='radio' for='age1'><input type='radio' name='age' value='1' id='age1' />18 to 24 years old</label> 
            <label class='radio' for='age2'><input type='radio' name='age' value='2' id='age2' />&gt; 24 years old</label> 
        </div>
        <div class="span12 question" data-question='2'>
            <h1 class='text-center'>2. Are you in need of a green environment?</h1>
            <label class='radio' for='park0'><input type='radio' name='park' value='0' id='park0'  />Yes, nature is my second name.</label> 
            <label class='radio' for='park1'><input type='radio' name='park' value='1' id='park1' />Yes, but I don't need it everyday.</label> 
            <label class='radio' for='park2'><input type='radio' name='park' value='2' id='park2' />No, not really.</label> 
        </div>
        <div class="span12 question" data-question='3'>
            <h1 class='text-center'>3. Do you have any kids?</h1>
            <label class='radio' for='child0'><input type='radio' name='child' value='0' id='child0'  />Yes, I have teenager kids.</label> 
            <label class='radio' for='child1'><input type='radio' name='child' value='1' id='child1' />Yes, I have little children.</label> 
            <label class='radio' for='child2'><input type='radio' name='child' value='2' id='child2' />Yes, but they already left the house.</label> 
            <label class='radio' for='child3'><input type='radio' name='child' value='3' id='child3' />Yes, they already left the house but I am planning to get a new baby.</label> 
            <label class='radio' for='child4'><input type='radio' name='child' value='4' id='child4' />No, but I am planning to get children soon.</label> 
            <label class='radio' for='child5'><input type='radio' name='child' value='5' id='child5' />No.</label> 
        </div>
        <div class="span12 question" data-question='4'>
            <h1 class='text-center'>4. Do you like to live luxurious?</h1>
            <label class='radio' for='lux0'><input type='radio' name='lux' value='0' id='lux0'  />Yes, I need lots of comfort.</label> 
            <label class='radio' for='lux1'><input type='radio' name='lux' value='1' id='lux1' />Yes, but it I can live without.</label> 
            <label class='radio' for='lux2'><input type='radio' name='lux' value='2' id='lux2' />No, I hate not daring to live life to the fullest, just because of some expensive furniture, eg.</label> 
        </div>
        <div class="span12 question" data-question='5'>
            <h1 class='text-center'>5. Do you like a lot of diversity in your surroundings?</h1>
            <label class='radio' for='multic0'><input type='radio' name='multic' value='0' id='multic0'  />Yes</label> 
            <label class='radio' for='multic1'><input type='radio' name='multic' value='1' id='multic1' />I don't really care.</label> 
            <label class='radio' for='multic2'><input type='radio' name='multic' value='2' id='multic2' />No</label> 
        </div>
        <div class="span12 question" data-question='6'>
            <h1 class='text-center'>6. Do you like to read books?</h1>
            <label class='radio' for='bib0'><input type='radio' name='bib' value='0' id='bib0'  />Yes</label> 
            <label class='radio' for='bib1'><input type='radio' name='bib' value='1' id='bib1' />Yes, but I don't like to pay for them so I often go to the library.</label> 
            <label class='radio' for='bib2'><input type='radio' name='bib' value='2' id='bib2' />No</label> 
        </div>
        <div class="span12 question" data-question='7'>
            <h1 class='text-center'>7. Do you often work out?</h1>
            <label class='radio' for='sport0'><input type='radio' name='sport' value='0' id='sport0'  />Yes, I work out three times a week at least.</label> 
            <label class='radio' for='sport1'><input type='radio' name='sport' value='1' id='sport1' />Yes, every week.</label> 
            <label class='radio' for='sport2'><input type='radio' name='sport' value='2' id='sport2' />No, I am more the kind that works out for fun.</label> 
            <label class='radio' for='sport3'><input type='radio' name='sport' value='3' id='sport3' />No</label> 
        </div>
        <div class="span12 question" data-question='8'>
            <h1 class='text-center'>8. Are you very sociable?</h1>
            <label class='radio' for='social0'><input type='radio' name='social' value='0' id='social0'  />Yes, whenever I pass somebody on the street I immediately start talking to them.</label> 
            <label class='radio' for='social1'><input type='radio' name='social' value='1' id='social1' />Yes, I say hello to everyone from my street.</label> 
            <label class='radio' for='social2'><input type='radio' name='social' value='2' id='social2' />Yes, but I am not that kind of person to start talking to strangers.</label> 
            <label class='radio' for='social3'><input type='radio' name='social' value='3' id='social3' />No, I hate talking to other people, especially</label> 
        </div>
        <div class="span12 question" data-question='9'>
            <h1 class='text-center'>9. Do you drive a car?</h1>
            <label class='radio' for='car0'><input type='radio' name='car' value='0' id='car0'  />Yes, and I want a place with a garage.</label> 
            <label class='radio' for='car1'><input type='radio' name='car' value='1' id='car1' />Yes, but I always park my car in a public garage.</label> 
            <label class='radio' for='car2'><input type='radio' name='car' value='2' id='car2' />No.</label>
        </div>
        <div class="span12 question" data-question='10'>
            <h1 class='text-center'>10. Do you get support from the OCMW?</h1>
            <label class='radio' for='ocmw0'><input type='radio' name='ocmw' value='0' id='ocmw0'  />Yes</label> 
            <label class='radio' for='ocmw1'><input type='radio' name='ocmw' value='1' id='ocmw1' />No</label>
        </div>
        <div class="span12 question" data-question='11'>
            <h1 class='text-center'>11. What diploma did you get?</h1>
            <label class='radio' for='dib0'><input type='radio' name='dib' value='0' id='dib0'  />I graduated from college and got a masters degree.</label> 
            <label class='radio' for='dib1'><input type='radio' name='dib' value='1' id='dib1' />I graduated from college and got a bachelors degree.</label>
            <label class='radio' for='dib1'><input type='radio' name='dib' value='1' id='dib2' />I didn't go to college.</label>
        </div>
        <div class="span12 question" data-question='12'>
            <h1 class='text-center'>12. Do you regularly go out?</h1>
            <label class='radio' for='out0'><input type='radio' name='out' value='0' id='out0'  />Yes, twice a week.</label> 
            <label class='radio' for='out1'><input type='radio' name='out' value='1' id='out1' />Yes, once every two weeks.</label>
            <label class='radio' for='out2'><input type='radio' name='out' value='1' id='out2' />No</label>
        </div>
        <div class="span12">
            <ul class="pager">
                <li class="previous">
                    <a href="#" onclick='previous();'>&larr; Previous</a>
                </li>
                <li class="next">
                    <a href="#" onclick='next();'>Next &rarr;</a>
                </li>
            </ul>
        </div>
        
    </div>
</div>