<section id="content">
    <div id="choose-data">
        <h3>[ CHOOSE YOUR DATA ]</h3>
        <ul>
            <li><a href="#" title="Basisscholen" onclick="getData(1)">Primary schools</a></li>
            <li><a href="#" title="Ziekenhuizen" onclick="getData(2)">Hospitals</a></li>
            <li><a href="#" title="Bioscopen" onclick="getData(3)">Cinemas</a></li>
            <li><a href="#" title="Dierenartsen" onclick="getData(4)">Veterinary practices</a></li>
            <li><a href="#" title="Kotzones" onclick="getData(5)">Zones of studenthousing</a></li>
            <li><a href="#" title="Parkings" onclick="getData(6)">Parkings</a></li>
            <li><a href="#" title="Secundaire schoole" onclick="getData(7)">High schools</a></li>
            <li><a href="#" title="Gezondheidscentra" onclick="getData(8)">Health infrastructures</a></li>
            <li><a href="#" title="Bibliotheken" onclick="getData(9)">Libraries</a></li>
            <li><a href="#" title="Apotheken" onclick="getData(10)">Pharmacies</a></li>
        </ul>
    </div>
    <div id="show-data">
        <h3>[ YOUR DATA ]</p>
        <div id="output">
            <div id="map_canvas" style="width:97%;height:300px;"></div>
        </div>
    </div>
</section>
              
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqsjbo0JTyqexEzIBOYcolZlo5SBUGrHc&sensor=true">
</script>
