<?php echo $this->form->renderForm(false) ?>
<h2 data-role="header" class="ui-header ui-bar-a ui-title" role="banner" role="heading" aria-level="1">Retrieve password</h2>
    <span class="closeBtn btn">X</span>        
    
    <?php 
        if(isset($this->error)) {
            echo "<p>" . $this->error . "</p>";
        }
    ?>
    
    <?php foreach ($this->form->getElements() as $element): ?>
       <?php echo $element ?>
    <?php endforeach; ?>
</form>