<div class="span12 centered firstblock clearfix">
    <div class="row">
        <div class="span6">
           <img src="<?php echo $this->baseUrl("/_assets/img/login-img.png") ?>" id="login-img" />
        </div>
        <div class="span5 offset1">
            <h1 class="">Login</h1>
            <?php echo $this->form ?>
                

                <?php 
                    if(isset($this->error)) {
                        echo "<p>" . $this->error . "</p>";
                    }
                ?>
            </form>
        </div>
    </div>
</div>