<?php echo $this->form->renderForm(false) ?>
    <h2 data-role="header" class="ui-header ui-bar-a ui-title" role="banner" role="heading" aria-level="1">Login panel</h2>
    <span class="closeBtn btn">X</span>
    <a href="<?php echo $this->url(
                array('controller'=>'account', 'action' => 'forgotpassword'),
                'default',
                true) ?>" title="Forgot password?" class="txtForgot">Forgot password?</a>

    <?php 
        if(isset($this->error)) {
            echo "<p>" . $this->error . "</p>";
        }
    ?>
     <?php foreach ($this->form->getElements() as $element): ?>
        <?php echo $element ?>
     <?php endforeach; ?>
</form>