<footer>
    <div class="span12 centered clearfix">
        <div class="row">
            <div class="span6">
                <h1>About</h1>
                <p>
                    Made in assignment of the <br/><a href="http://www.arteveldehs.be" title="Artevelde University College Ghent website">Artevelde University College Ghent</a>.<br/>
                    &copy; 2012-2013
                </p>
            </div>
            <div class="span6">
                <div class="row">
                    <div class="span2 footer-img">
                        <img src="<?php echo $this->baseUrl('_assets/img/me.png') ?>" class="img-polaroid img-me" />
                    </div>
                    <h1>Who am I</h1>
                    <p>
                        <a href="http://www.twitter.com/stefchri" title="Stefchri on Twitter">@StefChri</a><br/>
                        Stefaan Christiaens<br/>
                        <em>"I love coding, especially back end"</em>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>