<?php
    $loggedin = false;
    $auth = Zend_Auth::getInstance();
    $id = $auth->getStorage()->read()['id'];
    $userM = new Application_Model_UserMapper();
    try {   
        if($user = new Application_Model_User($userM->read($id)))
        {
            $loggedin = true;
            $username = $user->getUsername();
        }
    }
    catch (Exception $e)
    {
        $loggedin = false;;
    }
?>

<header>
    <div id="logo">
        <h1><a class="logo" href="<?php 
            echo $this->url( array('controller'=>'index', 'action' => 'index'),'default',true) 
        ?>" title="StatGhent Home">[startInGhent]</a></h1>
    </div>
    
    <section id="nav-desktop">
        <div id="buttons-header">
            <?php if($loggedin): ?>
            
                <a href="<?php echo $this->url(array('controller'=>'profile', 'action' => 'index'),'default',true) ?>"
                   class="btn btn-primary"><?php echo ucfirst($username) ?></a>
                <a href="<?php echo $this->url(array('controller'=>'account', 'action' => 'logout'), 'default', true) ?>" 
                   class="btn btn-secondary">Logout</a>
                <a href="<?php echo $this->url(array('controller'=>'profile', 'action' => 'list'), 'default', true) ?>" 
                   class="btn btn-secondary">People</a>
            <?php else: ?>
            
                <a href="<?php echo $this->url(array('controller'=>'account', 'action' => 'login'),'default',true) ?>"
                   class="btn btn-primary btn-login">Login</a>
                <a href="<?php echo $this->url(array('controller'=>'account', 'action' => 'register'), 'default', true) ?>" 
                   class="btn btn-secondary btn-register">Register</a>
            
            <?php endif; ?>
         </div>
     </section> 
</header>