<?php
    $loggedin = false;
    $auth = Zend_Auth::getInstance();
    $id = $auth->getStorage()->read()['id'];
    $userM = new Application_Model_UserMapper();
    try {   
        if($user = new Application_Model_User($userM->read($id)))
        {
            $loggedin = true;
            $username = $user->getUsername();
        }
    }
    catch (Exception $e)
    {
        $loggedin = false;;
    }
?>
<header>
    <div class="span12 centered">
        <div class="row">
            <div class="span6">
                <div id="logo"><a href="<?php echo $this->url(array('controller'=>'index', 'action' => 'index'),'default',true) ?>" title="Home StartInGhent"></a></div>
            </div>

            <div class="span6 navigation clearfix">
                <ul class="nav nav-pills pull-right">
                    <?php if($loggedin): ?>

                        <li><a title="Profile" href="<?php echo $this->url(array('controller'=>'profile', 'action' => 'index'),'default',true) ?>"><?php echo ucfirst($username) ?></a></li>
                        <li><a title="Logout" href="<?php echo $this->url(array('controller'=>'account', 'action' => 'logout'), 'default', true) ?>">Logout</a></li>
                        <li><a title="People" href="<?php echo $this->url(array('controller'=>'profile', 'action' => 'list'), 'default', true) ?>">People</a></li>
                        
                    <?php else: ?>

                        <li><a title="Login" href="<?php echo $this->url(array('controller'=>'account', 'action' => 'login'),'default',true) ?>">Login</a></li>
                        <li><a title="Register" href="<?php echo $this->url(array('controller'=>'account', 'action' => 'register'), 'default', true) ?>">Register</a></li>

                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
</header>