<?php echo $this->doctype() . "\n"; ?>
<html lang="en" >
    <head>
        <?php 
            echo $this->headMeta() . "\n" 
            . $this->headTitle() . "\n" 
            . $this->headLink() . "\n" 
            . $this->headScript() . "\n" ;
        ?>
    </head>
    <body>
    <?php 
        echo  $this->render('header.phtml') . "\n"; 
    ?>
        
        <div id="container">
            
    <?php echo
        $this->layout()->content . "\n" . $this->render('disclaimer.phtml'); 
    ?>
            
        </div>
        <div id="overlay"></div>
    <?php echo
        $this->render('footer.phtml') . $this->inlineScript() ."\n";
    ?>
    </body>
</html>