<div class="span12 centered firstblock clearfix bottom-block">
        <h1>Hey <strong>stranger</strong>,you can't go there!</h1>

        <p class="lead"><a title='home' href="<?php echo WEB_BASE_PATH . "index" ?>">Follow the breadcrums and go to Home.</a></p>
        <p class="lead"><a title='login' href="<?php echo WEB_BASE_PATH . "account/login" ?>">Login if you have an account.</a></p>
        <p class="lead"><a title='register' href="<?php echo WEB_BASE_PATH . "account/register" ?>">If not, register to really take advantage of this application.</a></p>
</div>