<div class="span12 centered firstblock clearfix bottom-block">
    <div class="row">
        <div class="span7 breath-bottom">
            <h1>Edit your profile</h1>
            <?php echo $this->form ?>
                <?php 
                    if(isset($this->error)) {
                        echo "<p>" . $this->error . "</p>";
                    }
                ?>
            </form>
            <a href="<?php echo $this->url(
                array('controller'=> 'profile', 'action'=>'index'),
                'default',
                true) ?>" class="btn btn-warning">Cancel</a>
        </div>
    </div>
</div>