<h1>Welcome <?php echo $this->username ?></h1>
<h2><?php echo $this->firstname ?> <?php echo $this->surname ?></h2>
<h2>Email: <a href="mailto:<?php echo $this->email ?>"><?php echo $this->email ?></a></h2>
<?php if (!empty($this->description)):?>
    <p><strong>About <?php echo $this->firstname ?>:</strong> <?php echo $this->description ?></p>
<?php endif; ?> 

<img src="<?php echo $this->baseUrl() ?>/images/<?php echo $this->avatar ;?>" alt="avatar-<?php echo $this->username ?>" />
<a href="<?php echo $this->url(
    array('controller'=>'profile', 'action' => 'edit'),
    'default',
    true) ?>">Edit Profile</a>
<a href="<?php echo $this->url(
    array('controller'=>'account', 'action' => 'logout'),
    'default',
    true) ?>">Logout</a>
        
