<div class="span12 centered firstblock clearfix  bottom-block">
    <h1>People using StartInGhent to find their ideal location in Ghent</h1>
    <br/>
    <?php foreach ($this->users as $user): ?>
    <div class="row">
        <div class="span12 user">
            <div class="row">
                <div class="span2 list-pic">
                    <img class="img-polaroid" src="<?php 
                    if ($user->getAvatar() == null) {
                        echo WEB_BASE_PATH . "_assets/img/person-placeholder.jpg";
                    }
                    else {
                        echo WEB_BASE_PATH . "images/" . $user->getAvatar();
                    }
                    
                    ?>" />
                </div>
                <div class="span10">
                    <h1><?php echo $user->getUsername(); ?></h1>
                    <?php if ($user->getAnswers() == null): ?>
                    <p class="lead lead-push">
                        <?php echo $user->getUsername(); ?> hasn't searched for the best place to start yet.
                    </p>
                    <?php else: ?>
                    <a class="btn btn-bottom-users" href="<?php echo $this->url(
                                                            array('controller'=>'profile', 'action' => 'answers'),
                                                            'default',
                                                            true) . "?id=" . $user->getId() ?>">Check where <?php echo $user->getUsername(); ?> should start</a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <?php endforeach;?>
    <div class="row">
        <div class="span12">
            <a id="btn-statistics" class="btn btn-success btn-block btn-large" href="<?php echo $this->url(
                        array('controller'=>'profile', 'action' => 'statistics'),
                        'default',
                    true);?>" title="Statisctics">Statistics</a>
        </div>
    </div>
</div>