<div class="span12 centered firstblock clearfix">
    <?php foreach ($this->users as $user): ?>
    <div class="row">
        <div class="span12 user">
            <div class="row">
                <div class="span3">
                    <img class="img-polaroid" src="<?php 
                    if ($user->getAvatar == null) {
                        echo WEB_BASE_PATH . "/_assets/img/person-placeholder.jpg";
                    }
                    else {
                        
                    }
                    echo WEB_BASE_PATH . "/images/" . $user->getAvatar();
                    ?>" />
                </div>
                <div class="span9">
                    <h1><?php echo $user->getUsername(); ?></h1>
                    <?php if ($user->getAnswers() == null): ?>
                    <p class="lead lead-push">
                        <?php echo $user->getUsername(); ?> hasn't searched for the best place to start yet.
                    </p>
                    <?php else: ?>
                    <a class="btn btn-bottom-users" href="<?php echo $this->url(
                                                            array('controller'=>'profile', 'action' => 'answers'),
                                                            'default',
                                                            true) . "/" . $user->getId() ?>">Check where <?php echo $user->getUsername(); ?> should start</a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <?php endforeach;?>
</div>