<?php 
    $this->inlineScript()
         ->appendFile($this->baseUrl('_scripts/js/statistics.js')) 
    ;
?>

<div class="span12 centered firstblock clearfix bottom-block">
    <h1>Statistics of StartInGhent</h1>
    <p class="lead total"></p>
    <div id="images" class="clearfix"></div>
    <h2>How were the questions answered?</h2>
    
    <div class="span12 answer" data-question='1'>
        <h3>1. How old are you?</h3>
        <div class="span6" data-answer="0">
            <p class="lead">8 to 24 years old.</p>
        </div> 
        <div class="span6" data-answer="1">
            <p class="lead">24 years old or older.</p>
        </div> 
    </div>
    <div class="span12 answer" data-question='2'>
        <h3 class='text-center'>2. Are you in need of a green environment?</h3>
        <div class="span6" data-answer="0">
            <p class="lead">Yes, nature is my second name.</p>
        </div> 
        <div class="span6" data-answer="1">
            <p class="lead">Yes, but I don't need it everyday.</p>
        </div> 
        <div class="span6" data-answer="2">
            <p class="lead">No, not really.</p>
        </div> 
    </div>
    <div class="span12 answer" data-question='3'>
        <h3 class='text-center'>3. Do you have any kids?</h3>
        <div class="span6" data-answer="0">
            <p class="lead">Yes, I have teenager kids.</p>
        </div> 
        <div class="span6" data-answer="1">
            <p class="lead">Yes, I have little children.</p>
        </div> 
        <div class="span6" data-answer="2">
            <p class="lead">Yes, but they already left the house.</p>
        </div> 
        <div class="span6" data-answer="3">
            <p class="lead">Yes, they already left the house but I am planning to get a new baby.</p>
        </div> 
        <div class="span6" data-answer="4">
            <p class="lead">No, but I am planning to get children soon.</p>
        </div> 
        <div class="span6" data-answer="5">
            <p class="lead">No.</p>
        </div> 
    </div>
    <div class="span12 answer" data-question='4'>
        <h3 class='text-center'>4. Do you like to contribute to the neighborhood?</h3>
        <div class="span6" data-answer="0">
            <p class="lead">Yes, I want to participate weekly.</p>
        </div> 
        <div class="span6" data-answer="1">
            <p class="lead">Yes, but not to actively.</p>
        </div> 
        <div class="span6" data-answer="2">
            <p class="lead">No</p>
        </div> 
    </div>
    <div class="span12 answer" data-question='5'>
        <h3 class='text-center'>5. Do you take public transportation to work?</h3>
        <div class="span6" data-answer="0">
            <p class="lead">Yes</p>
        </div> 
        <div class="span6" data-answer="1">
            <p class="lead">No</p>
        </div> 
    </div>
    <div class="span12 answer" data-question='6'>
        <h3 class='text-center'>6. Do you like to read books?</h3>
        <div class="span6" data-answer="0">
            <p class="lead">Yes</p>
        </div> 
        <div class="span6" data-answer="1">
            <p class="lead">Yes, but I don't like to pay for them so I often go to the library.</p>
        </div> 
        <div class="span6" data-answer="2">
            <p class="lead">No</p>
        </div> 
    </div>
    <div class="span12 answer" data-question='7'>
        <h3 class='text-center'>7. Do you often work out?</h3>
        <div class="span6" data-answer="0">
            <p class="lead">Yes, I work out three times a week at least.</p>
        </div> 
        <div class="span6" data-answer="1">
            <p class="lead">Yes, every week.</p>
        </div> 
        <div class="span6" data-answer="2">
            <p class="lead">No, I am more the kind that works out for fun.</p>
        </div> 
        <div class="span6" data-answer="3">
            <p class="lead">No</p>
        </div> 
    </div>
    <div class="span12 answer" data-question='8'>
        <h3 class='text-center'>8. Do you drive a car?</h3>
        <div class="span6" data-answer="0">
            <p class="lead">Yes, and I want a place with a garage.</p>
        </div> 
        <div class="span6" data-answer="1">
            <p class="lead">Yes, but I always park my car in a public garage.</p>
        </div> 
        <div class="span6" data-answer="2">
            <p class="lead">No</p>
        </div> 
    </div>
    <div class="span12 answer" data-question='9'>
        <h3 class='text-center'>9. Do you get support from the OCMW?</h3>
        <div class="span6" data-answer="0">
            <p class="lead">Yes</p>
        </div> 
        <div class="span6" data-answer="1">
            <p class="lead">No</p>
        </div> 
    </div>
    <div class="span12 answer" data-question='10'>
        <h3 class='text-center'>10. Do you have pets?</h3>
        <div class="span6" data-answer="0">
            <p class="lead">Yes, a dog.</p>
        </div> 
        <div class="span6" data-answer="1">
            <p class="lead">Yes, but no dogs.</p>
        </div> 
        <div class="span6" data-answer="2">
            <p class="lead">No</p>
        </div> 
    </div>
    <div class="span12 answer" data-question='11'>
        <h3 class='text-center'>11. Do you regularly go out to see a movie?</h3>
        <div class="span6" data-answer="0">
            <p class="lead">Yes, once every month.</p>
        </div> 
        <div class="span6" data-answer="1">
            <p class="lead">No</p>
        </div> 
    </div>
    
</div>
<script>
    var _baseUrl = "<?php echo WEB_BASE_PATH; ?>";
</script>